In [1]:
import cProfile

In [50]:
import numpy as np
position = np.array([[1,0],[0,0],[0,2]])
origin = np.array([[0,0]])
from scipy.spatial.distance import pdist
from scipy.spatial.distance import cdist

#print(pdist(position))
A = cdist(position,position)
print(cdist(origin,position))

[[1. 0. 2.]]


In [7]:
import os 
os.system('python3 operator.py')

0

In [26]:
np.zeros([5,2]).sum(axis=0)

array([0., 0.])

In [12]:
origin = np.array([[0,0]])
print(cdist(origin,position))

[[1. 0. 2.]]


In [41]:
A = np.array([[1,2,4,5,6]])
B = np.array([[2,3,4,5,6]])

print(A*B)
atest = np.array([A-1,A,A+1])
btest = np.array([B-1,B,B+1])
print(np.vstack([A,B]))
print(np.transpose(np.vstack([[A,B]])))


[[ 2  6 16 25 36]]
[[1 2 4 5 6]
 [2 3 4 5 6]]
[[[1 2]]

 [[2 3]]

 [[4 4]]

 [[5 5]]

 [[6 6]]]


In [43]:
A[A<=3] = 100

In [44]:
print(A)

[[100 100   4   5   6]]


In [45]:
B = np.random.normal(B,abs(B)/10)

In [46]:
print(B)

[[2.01869686 2.92507595 3.71386702 4.64732588 7.54031108]]


In [48]:
B[B>3]= 1

In [49]:
print(B)

[[2.01869686 2.92507595 1.         1.         1.        ]]


In [ ]:
print